apiVersion: apps/v1
kind: Deployment
metadata:
  name: testlink
  namespace: devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testlink
  template:
    metadata:
      labels:
        app: testlink
    spec:
      containers:
      - name: testlink
        image: bitnami/testlink
        ports:
        - containerPort: 80
      volumes:
      - name: testlink-data
        persistentVolumeClaim:
          claimName: testlink-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: testlink
  namespace: devops
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30003
  selector:
    app: testlink
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: testlink-pvc
  namespace: devops
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
